---
- template:
    src: make.conf
    dest: /etc/portage/make.conf

- file:
    state: directory
    name: /var/lib/portage/distfiles

- get_url:
    url: "{{ item.url }}"
    dest: "/var/lib/portage/distfiles/{{ item.dest }}"
    checksum: "sha1:{{ item.checksum }}"
  with_items:
    - { url: 'https://github.com/mgorny/python-exec/releases/download/python-exec-2.0.2/python-exec-2.0.2.tar.bz2', dest: 'python-exec-2.0.2.tar.bz2', checksum: '238bea3142152e7235327315fd4062e613ae5fba' }
    - { url: 'https://dev.gentoo.org/~vapier/dist/gnuconfig-20150727.tar.bz2', dest: 'gnuconfig-20150727.tar.bz2', checksum: 'fbf17e403d1ad373cad2beced5f8bcde57168c58' }
    - { url: 'https://dev.gentoo.org/~vapier/dist/gnuconfig-20151214.tar.bz2', dest: 'gnuconfig-20151214.tar.bz2', checksum: '2b1fc11a270040aa4e43954f2aa25409d88a1cba' }
    - { url: 'https://dev.gentoo.org/~vapier/dist/net-tools-1.60_p20141019041918.tar.xz', dest: 'net-tools-1.60_p20141019041918.tar.xz', checksum: '99d411e2379ede3807bc79506518d6d8590bf05e' }
    - { url: 'https://dev.gentoo.org/~vapier/dist/net-tools-1.60_p20141019041918-patches-1.tar.xz', dest: 'net-tools-1.60_p20141019041918-patches-1.tar.xz', checksum: '59b4f0b1a34a08cfadb4408a9bfd05c56392c6c5' }
    - { url: 'https://dev.gentoo.org/~vapier/dist/gnuconfig-20150727.tar.bz2', dest: 'gnuconfig-20150727.tar.bz2', checksum: 'fbf17e403d1ad373cad2beced5f8bcde57168c58' }
    - { url: 'https://xyinn.org/gentoo/distfiles/code2color-0.2', dest: 'code2color-0.2', checksum: 'f9deb4d14cea554b59ec979be5cb3eda35aff4dd' }
    - { url: 'https://xyinn.org/gentoo/distfiles/ca-certificates_20151214.tar.xz', dest: 'ca-certificates_20151214.tar.xz', checksum: 'c993a9a44cf2bf2d7282699fd0415f2b5d52fa00' }
    - { url: 'https://xyinn.org/gentoo/distfiles/procps-3.3.11-remove_Unix98_output_limits.patch', dest: 'procps-3.3.11-remove_Unix98_output_limits.patch', checksum: 'b03372c638a96162825d51024365ac1184666e28' }
    - { url: 'https://www.jabawok.net/gentoo/distfiles/openssh-7.2_p1-sctp.patch.xz', dest: 'openssh-7.2_p1-sctp.patch.xz', checksum: 'ec1bc931fc694cd8d00ab7ad9a78370946655d81' }
    - { url: 'https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_21_RTM/src/nss-3.21.tar.gz', dest: 'nss-3.21.tar.gz', checksum: 'd4bbbd72b967443e8b65f504cdd157e3df93a84a' }
    - { url: 'https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz', dest: 'openssl-1.0.2g.tar.gz', checksum: '36af23887402a5ea4ebef91df8e61654906f58f2' }
    - { url: 'https://ftp.openssl.org/source/old/1.0.2/openssl-1.0.2h.tar.gz', dest: 'openssl-1.0.2h.tar.gz', checksum: '577585f5f5d299c44dd3c993d3c0ac7a219e4949' }
  loop_control:
    label: "{{ item.dest }}"
